using System.Text;
using Openza.Tasks.Core.Models;

namespace Openza.Tasks.Core.Services;

public static class MarkdownExporter
{
    public static string Export(IReadOnlyList<TaskItem> tasks, IReadOnlyList<ProjectItem> projects, IReadOnlyList<LabelItem> labels)
    {
        var projectById = projects.ToDictionary(p => p.Id, StringComparer.Ordinal);
        var groupedTasks = tasks.GroupBy(t => t.ProjectId).OrderBy(group =>
        {
            if (group.Key is null || !projectById.TryGetValue(group.Key, out var project))
            {
                return "zzzz-No Project";
            }

            return project.IsFavorite ? $"0000-{project.Name}" : project.Name;
        }, StringComparer.CurrentCultureIgnoreCase);

        var buffer = new StringBuilder();
        buffer.AppendLine("# Openza Tasks Export");
        buffer.AppendLine();
        buffer.AppendLine($"Export Date: {DateTimeOffset.Now:yyyy-MM-dd HH:mm}");
        buffer.AppendLine($"Total Tasks: {tasks.Count} (Active: {tasks.Count(t => !t.IsCompleted)}, Completed: {tasks.Count(t => t.IsCompleted)})");
        buffer.AppendLine($"Total Projects: {projects.Count}");
        buffer.AppendLine($"Total Labels: {labels.Count}");
        buffer.AppendLine();
        buffer.AppendLine("---");
        buffer.AppendLine();
        buffer.AppendLine("## Projects & Tasks");
        buffer.AppendLine();

        foreach (var group in groupedTasks)
        {
            var projectName = group.Key is not null && projectById.TryGetValue(group.Key, out var project)
                ? project.Name
                : "No Project";
            buffer.AppendLine($"### {Escape(projectName)}");
            buffer.AppendLine();

            foreach (var task in group.OrderBy(t => t.IsCompleted).ThenBy(t => t.Priority).ThenBy(t => t.DueDate))
            {
                WriteTask(buffer, task);
            }

            buffer.AppendLine();
        }

        if (labels.Count > 0)
        {
            buffer.AppendLine("---");
            buffer.AppendLine();
            buffer.AppendLine("## Labels");
            buffer.AppendLine();
            buffer.AppendLine("| Name | Color | Source |");
            buffer.AppendLine("|------|-------|--------|");
            foreach (var label in labels.OrderBy(l => l.Name, StringComparer.CurrentCultureIgnoreCase))
            {
                buffer.AppendLine($"| {Escape(label.Name)} | {label.Color} | {SourceName(label.IntegrationId)} |");
            }

            buffer.AppendLine();
        }

        buffer.AppendLine("---");
        buffer.AppendLine();
        buffer.AppendLine("*Generated by Openza Tasks*");
        return buffer.ToString();
    }

    private static void WriteTask(StringBuilder buffer, TaskItem task)
    {
        var metadata = new List<string>();
        if (task.Priority != 4)
        {
            metadata.Add(task.Priority switch
            {
                1 => "Priority: High",
                2 => "Priority: Medium",
                3 => "Priority: Normal",
                _ => "Priority: Low",
            });
        }

        if (task.DueDate is not null)
        {
            metadata.Add($"Due: {task.DueDate:yyyy-MM-dd}");
        }

        var labelTags = string.Join(' ', task.Labels.Select(l => $"@{l.Name.Replace(' ', '_')}"));
        buffer.Append("- ");
        buffer.Append(task.IsCompleted ? "[x] " : "[ ] ");
        buffer.Append(Escape(task.Title));
        if (metadata.Count > 0)
        {
            buffer.Append(" (");
            buffer.Append(string.Join(", ", metadata));
            buffer.Append(')');
        }

        if (!string.IsNullOrWhiteSpace(labelTags))
        {
            buffer.Append(' ');
            buffer.Append(labelTags);
        }

        buffer.AppendLine();

        if (!string.IsNullOrWhiteSpace(task.Description))
        {
            buffer.AppendLine($"  - _{Escape(task.Description)}_");
        }
    }

    private static string Escape(string text) =>
        text.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("*", "\\*", StringComparison.Ordinal)
            .Replace("_", "\\_", StringComparison.Ordinal)
            .Replace("`", "\\`", StringComparison.Ordinal)
            .Replace("[", "\\[", StringComparison.Ordinal)
            .Replace("]", "\\]", StringComparison.Ordinal)
            .Replace("|", "\\|", StringComparison.Ordinal);

    private static string SourceName(string integrationId) => integrationId switch
    {
        IntegrationIds.Todoist => "Todoist",
        IntegrationIds.MicrosoftToDo => "Microsoft To Do",
        IntegrationIds.Obsidian => "Obsidian",
        _ => "Openza Tasks",
    };
}
