name: Feature request
description: Suggest a feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea! Please describe the problem and the desired outcome.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      placeholder: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: What would you like to see built?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any alternatives you've considered?
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Mockups, links, or related issues.
    validations:
      required: false
